### ISSUE TITLE
Secure E7+

### ISSUE THREAD

**Issue by samsonrosen** [hankolsen/com.securemeters.horstmann#47]
Hi!

https://www.securemeters.com/uk/product/electric-water-heating-controls/e7/

Secure started making an ‘smart’ boiler switch. I live in the UK and I’m thinking of buying one to integrate into my homebridge/HomeKit smart home. I have a smart tariff with Octopus and long term I’d like to integrate my boilerr to heat up during cheaper energy times. 

Unfortunately the app is proprietary. The vendor said they have no short term plans for integrations. The device can be controlled locally with Bluetooth or WiFi. 

I noticed this plugin supports some secure devices. Have you got any plans to support the newer connected devices? I don’t own one yet but I’m about to buy one and I’d love to support the development (with ‘coffee’).

I just use homebridge is all but there are lots of homebridge plugins that can be based on community made HTTPS or BLE APIs..

Let me know what you think. I’ve seriously scoured the Internet and no one’s writing plugins for these devices.

Thanks,

San

**Comment by hankolsen** [comment]
Hi @samsonrosen!

Thank you for reaching out.

First of all, since Homey labels this app as a "Community app" it only works on Homey Pro. I'm not sure about Homey Bridge, but my guess is that it is not possible to install this app on Homey Bridge.

Secondly, all the drivers implemented so far in this app are using z-wave, but the e7+ seems to be Bluetooth if I understand it correctly.
I don't have any experience working with Bluetooth devices in Homey, and I do not own any device to test the development on, so I'd say that the chances are quite low that it will be possible for me to add support for it. I'd happy to consider PRs, but I don't think I will be able to implement it myself.

Best regards,
Hank

**Comment by samsonrosen** [comment]
Thanks for taking the time to reply! Yeah I thought the protocol was different. You are correct about it being Bluetooth.

I’ll see what tools are out there to see if there’s an easy way to capture packets and reverse engineer it into a simple on / off homebridge plugin.
